version: '3.8'
services:
  dev-db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookmark-db
    ports:
      - 5432:5432
    networks:
      - bookmark-network-nest

networks:
  bookmark-network-nest:
